<?php

$config = [
  // Turn on extra output during request & response
  'DEBUG' => false,

  // Used to access Canvas
  'canvas_base_url' => 'CANVAS_SUB_DOMAIN', // example: algonquin.instructure.com
  'canvas_api_key' => 'CANVAS_API_KEY',

  // Disallow older versions of Markbot that may not be testing everything required
  'min_markbot_version' => '2.10.0',

  // The passcode hash generated by Markbot from the MARKBOT_LOCK_PASSCODE environment variable
  'passcode_hash' => 'YOUR_MARKBOT_LOCK_PASSCODE_HASH',
];
